### ISSUE TITLE
Name conflicts with bin from Mozilla’s Network Security Services

### ISSUE THREAD

**Issue by maxbraeutigam** [arroyo/cmsutil#2]
Dear @arroyo - thank you very much for the great and easy tool. It’s working fine for me. I started writing a `PKGBUILD` file for Archlinux. Unfortunately, it will not install `cmsutil` because of a file conflict with `cmsutil` from Mozilla’s [Network Security Services](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS), [Archlinux package here](https://archlinux.org/packages/core/x86_64/nss/). I had to rename your binary to e.g. `cmsutil-graphcms`, but I guess that’s a bit clumsy.
Do you have an idea of a better name than `cmsutil`? Anyway, thanks a lot for your work!
Cheers,
Max

**Comment by arroyo** [comment]
Thanks Max, I ran across that tool after some google searches last year but thought it was obscure enough to not cause conflicts. I was wrong.  You brought up a great reason to rename the project, however.  I'll do some thinking about it...thanks for bringing it up.

**Comment by maxbraeutigam** [comment]
Cool, thank you very much. Indeed, lots of programs depend on nss under Linux, e.g. Firefox, Chromium, Tor, JRE, Libre office—just to mention a few.
